version: '3'

services:
  api:
    build: .
    restart: always
#    command: "devserver"
    ports:
      - $API_PORT:$API_PORT
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./investments-api:/app
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    restart: always
    ports:
      - 54322:5432
    volumes:
      - db_vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=investments

volumes:
  db_vol: {}
