"""initial

Revision ID: 1676969b2502
Revises: 
Create Date: 2019-05-31 10:36:05.997878

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
from api.models import InvestmentsPerformance

revision = '1676969b2502'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('investments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('usd_rate', sa.Float(), nullable=False),
    sa.Column('open_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('close_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investments_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=False),
    sa.Column('period_type', sqlalchemy_utils.types.choice.ChoiceType(InvestmentsPerformance.PeriodTypes.CHOICES,
                                                                      impl=sa.Integer()), nullable=False,
              server_default=str(InvestmentsPerformance.PeriodTypes.MONTH)),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('profitability_coeff', sa.Float(), nullable=False),
    sa.Column('profitability_coeff_total', sa.Float(), nullable=False),
    sa.Column('profit', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investments_performance')
    op.drop_table('investments')
    op.drop_table('users')
    op.drop_table('instruments')
    # ### end Alembic commands ###
